names:
- PPPMM
- PPPDD
- VICFX
- PIBSA
- ZEAMX
- SOLTU
- SPQOL
- BEAVA
- CIRAR
- BRSOL
- FAGES
- 1LUPG
- PSEZ
nc: 13
path: /data/rwm_dataset_extraction/yolov11
test: images/test
train: images/train
val: images/val
